cripto-provider:
   ripio:
      protocolo: ${CRYPTO_PROTOCOL:https}
      dominio: ${CRYPTO_DOMAIN:sandbox-b2b.ripio.com} 
      apis:
         login: ${CRYPTO_PATH_LOGIN:/oauth2/token/}
         cotizar: ${CRYPTO_PATH_COTIZAR:/api/v1/reusable-quotes/}
         clienteCrear: ${CRYPTO_PATH_CLIENTECREAR:/api/v1/end-users/}
         operacionCrear: ${CRYPTO_PATH_CLIENTECREAR:/api/v1/reusable-quotes/:reusableQuoteId/actions/execute/}
      seguridad:
         clienteId: ${CRYPTO_CLIENT_ID}
         clienteSecreto: ${CRYPTO_CLIENT_SECRET}		 
server:
   error:
      whitelabel:
         enabled: false
   servlet:
      context-path: /cripto-provider
   tomcat:
      max-threads: 1024

spring:
   application:
      name: cryptoProvider
   datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
      url: ${DATABASE_URL}
#      url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=sisa-dbdev01)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=SISADEV)))
      max-idle: 1000
      max-wait: 1000000
      min-idle: 5
      initial-size: 5
      hikari:
         connection-init-sql: alter session set nls_date_format = 'DD/MM/YYYY'  
   jpa:
      properties:
         hibernate:
            format_sql: true
            default_schema: SISAOWN
      show-sql: true
   jackson:
      deserialization:
         fail-on-unknown-properties: true
          
management:
   endpoints:
      web:
         exposure:
            include: health,info,liveness,readiness
      health: 
         enabled: true
   security:
      enabled: false

#logging:
#   level:
#      org: 
#         hibernate:
#            SQL: TRACE
#            type:
#               descriptor:
#                  sql:
#                     BasicBinder: TRACE
#         springframework: TRACE
            
