cripto-provider:
   ripio:
      seguridad:
         clienteId: ${CRYPTO_CLIENT_ID}
         clienteSecreto: ${CRYPTO_CLIENT_SECRET}
server:
   port: 8081
spring:
   datasource:
      username: diego.bueno
      password: vRSZrzHO6S
      url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=sisa-dbdev01)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=SISADEV)))
logging:
   level:
      root: DEBUG