server:
   servlet:
      context-path: /cripto-provider
   error:
      whitelabel:
         enabled: false
spring:
   application:
      name: cryptoProvider
   jackson:
       deserialization:
          fail-on-unknown-properties: true
cripto-provider:
   ripio:
      protocolo: ${CRYPTO_PROTOCOL:https}
      dominio: ${CRYPTO_DOMAIN:sandbox-b2b.ripio.com} 
      apis:
         login: ${CRYPTO_PATH_LOGIN:/oauth2/token/}
         cotizar: ${CRYPTO_PATH_COTIZAR:/api/v1/reusable-quotes/}
         clienteCrear: ${CRYPTO_PATH_CLIENTECREAR:/api/v1/end-users/}
         operacionCrear: ${CRYPTO_PATH_OPERACIONCREAR:/api/v1/reusable-quotes/:reusableQuoteId/actions/execute/}
         cotizacionConsul: ${CRYPTO_PATH_COTIZAR:/api/v1/reusable-quotes/}
      seguridad:
         clienteId: ${CRYPTO_CLIENT_ID}
         clienteSecreto: ${CRYPTO_CLIENT_SECRET}		 
#management:
#   endpoints:
      #web:
         #exposure:
            #include: health,info,liveness,readiness
      #health: 
         #enabled: true
   #security:
      #enabled: false