cripto-provider:
   ripio:
      seguridad:
         clienteId: ${CRYPTO_CLIENT_ID}
         clienteSecreto: ${CRYPTO_CLIENT_SECRET}
spring:
   output:
      ansi:
         enabled: always
server:
   port: 8093
   #output:
    #  ansi:
     #    enabled: always
logging:
   level:
      root: ERROR
      com:
         davalores: TRACE
   pattern:
      console: "%clr(%d{mm:ss.SSS}){yellow} %clr(%.-3level) %clr(%-35.35logger{0}) %msg %n"